theme: jekyll-theme-cayman
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: Transferencia de Estilo
